### ISSUE TITLE
1009: An error occurs when starting the playback device. Check the playback device.

### ISSUE THREAD

**Issue by 345ml** [AgoraIO-Extensions/react-native-agora#674]
This is a question.

I am encountering an error in the title.
This error occurs irregularly and I do not know in what case this is reproduced.

https://github.com/AgoraIO-Extensions/react-native-agora/blob/762259b81587da7c9970e36834f087ee9c910950/src/AgoraBase.ts#L404C2-L404C2

This error can be seen in the onError event when joinChannel is executed.

I cannot guess the cause by looking at the error description.
I do not know the procedure to reproduce the error.
Is it related to audio devices?

Do you happen to know anything about this?

## Environment
 - Device: iPhone SE 2 gen
 - OS: iOS 16.5.1
 - react-native: 0.71.6
 - react-native-agora: 4.1.2

**Comment by LichKing-2234** [comment]
is this error make some thing not working?

**Comment by 345ml** [comment]
@LichKing-2234 
Thanks.

I have implemented the onError event to close the channel if it catches an error.

Therefore, I have not checked if the call continues normally after the error occurs.

However, I did not consider the case where the connection continues after the error occurs.
It would be worth a try for that.

**Comment by mk0116** [comment]
I am consistently encountering a sequence of errors, specifically error codes 1009, 1011, and 1012, while running the application. Intriguingly, this set of errors always occur twice, in the following order:
onError 1009
onError 1011
onError 1012
onError 1009
onError 1011
onError 1012
This issue is consistently reproducible (100%) when the device receives an incoming call. The errors occur even when the call is not answered, merely ringing, and a new session is started in the application.

**Comment by mk0116** [comment]
When this occurs, I can hear other players' voices, but my voice isn't being heard.

**Comment by LichKing-2234** [comment]
the microphone will be occupied when the device receives an incoming call.
